services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-api
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    command: [ "java", "-jar", "app.jar" ]
    depends_on:
      - flyway

  flyway:
    image: flyway/flyway:11
    command: -connectRetries=60 -configFiles=/flyway/migration/flyway.conf migrate
    volumes:
      - ${PWD}/database:/flyway/migration
    depends_on:
      - postgres

  postgres:
    image: postgres:17.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=test_db
    restart: always
