spring:
  application:
    name: url-shortener-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user
    password: test_pass
  jpa:
    hibernate:
      ddl-auto: validate

cross-origin:
  origins: "http://localhost:5173/"

app:
  url-prefix: "http://localhost:8080/"
