flyway.url=jdbc:postgresql://postgres:5432/test_db
flyway.user=test_user
flyway.password=test_pass
flyway.locations=filesystem:/flyway/migration
flyway.schemas=url

flyway.placeholders.runMockData=true
